version: '1.0'
stages:
 - build
 - test
 - deploy
steps:

  BuildingDockerImage:
    title: Building Docker Image
    type: build
    stage: 'build'
    image_name: jumpst3r/printed-hw-segmentation
    working_directory: ./docker/
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile

  TestRunnable:
    title: Running Tests
    stage: 'test'
    image: jumpst3r/printed-hw-segmentation
    commands:
      - apt update && apt install python-pip python-setuptools python-dev build-essential --no-install-recommends -y
      - pip install wheel numpy scikit-image pytest
      - py.test

  PushingToDockerRegistry:
    type: push
    stage: 'deploy'
    title: Pushing To Dockerhub Registry
    candidate: jumpst3r/printed-hw-segmentation
    tag: 'latest'
    image_name: jumpst3r/printed-hw-segmentation
    registry: dockerhub
